language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower gulp
- bower install
- echo -e "Host giphy.kuznicki.me\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
before_install:
- openssl aes-256-cbc -K $encrypted_04c8809ecb9e_key -iv $encrypted_04c8809ecb9e_iv
  -in deploy.key.enc -out deploy.key -d
- chmod 600 deploy.key
after_success:
- gulp build
- scp -i deploy.key -r dist/* travis@giphy.kuznicki.me:giphy